name: Create version

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create new version
      - uses: actions/checkout@v1
        with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ GITHUB_REF }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          WORK_SPACE: ${{ github.workspace }}
          CI: true
      # if: ${{  }}
      #  ${WORK_SPACE}/.github/workflows/scripts/create-artifact.sh
