name: Create version

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-scope: [lint, unit, gemini]
        node-version: [12.14.1]

    steps:
      - uses: actions/checkout@v1
      - name: create new version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Lint's checks
        if: ${{ THREAD_NAME == 'lint' }}
        run: |
          npm run lint
        env:
          CI: true
          THREAD_NAME: ${{ matrix.test-scope }}
