name: Create version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: create new version
        run: ${WORK_SPACE}/.github/workflows/scripts/create-artifact.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          WORK_SPACE: ${{ github.workspace }}
          CI: true  

# on:
#   push:
#     branches:
#       - master
# jobs:
#   publish-gpr:
#     if: "!contains(github.event.head_commit.author.name, 'GITHUBACTION')"
#     runs-on: ubuntu-latest
#     steps:
#       ....
#       - name: Set up git for commits
#         run: |
#           git config user.name "GITHUBACTION"
#         timeout-minutes: 1
#       - name: Push
#         run: git push --follow-tags --no-verify origin HEAD:master
#         timeout-minutes: 1
#   empty-job:
#     # if no jobs run, github action considers it a test failure -- which seems like a bug
#     # this makes it so the top-level if statement for the job does not give status failure.
#     runs-on: ubuntu-latest
#     if: success()
#     steps:
#       - name: Meep
#         run: |
#           echo "This job will always succeed. If no jobs run, we still want the workflow to give status success."