name: Create version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: create new version
        run: ${{ github.workspace }}./scripts/create-artifact.sh
        env:
          CI: true