name: Create version

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-scope: [lint, unit, gemini]
        node-version: [12.14.1]

    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: yarn

      - name: check lints
        run: yarn test:eslint
        if: ${{ THREAD_NAME == 'lint' }}
        env:
          CI: true
          THREAD_NAME: ${{ matrix.test-scope }}

      - name: run all tests
        run: yarn test
        if: ${{ THREAD_NAME == 'unit' }}
        env:
          CI: true
          THREAD_NAME: ${{ matrix.test-scope }}
