name: Create version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create new version
        run: ls -a && cd .. && ls -a  
        env:
          CI: true