name: Create version

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-scope: [ lint, unit, gemini ]

    steps:
      - uses: actions/checkout@v1
      - name: create new version
        run: |
          echo ${THREAD_NAME}
        env:
          CI: true
          THREAD_NAME: ${{ matrix.test-scope }}
