name: Create version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: create new version
        run: yarn --frozen-lockfile && ./.github/workflows/scripts/create-artifact.sh && yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true