name: Create version

on:
  push:
    branches:
      - master

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: create new version
        run: echo 'Create new version onl y for master push ' && yarn --frozen-lockfile && yarn --cwd ${{ github.workspace }} semantic-release