name: Create version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create new version
        run: ${{ github.workspace }}/.github/workflows/scropts/create-artifact.sh