name: Create version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: create new version
        run: yarn --frozen-lockfile && yarn GH_TOKEN=${{ secrets.GITHUB_TOKEN }} semantic-release #${{ github.workspace }}/.github/workflows/scripts/create-artifact.sh
        env:
          CI: true